---

- name: Install python mysqldb
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    dpkg_options: 'force-confnew,force-confdef'
    autoclean: true
    autoremove: true
    update_cache: true
    cache_valid_time: 3600
  vars:
    packages:
    - python3-mysqldb

- name: Create all databases
  community.mysql.mysql_db:
    collation: "{{ item.collation | default(omit) }}"
    encoding: "{{ item.encoding | default(omit) }}"
    name: "{{ item.name | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
  with_items: "{{ mysql_grants_databases }}"

- name: Create all users
  community.mysql.mysql_user:
    host: "{{ item.host | default(omit) }}"
    host_all: "{{ item.host_all | default(omit) }}"
    name: "{{ item.name | default(omit) }}"
    password: "{{ item.password | default(omit) }}"
    priv: "{{ item.priv | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
  with_items: "{{ mysql_grants_users }}"

...
