---
- name: Converge 8.0
  hosts: all
  become: true
  become_method: ansible.builtin.sudo
  vars:
    percona_mysql_version: '8'
    percona_mysql_root_password: SOMELONGPASSWORD
    mysql_grants_databases:
    - name: mytest
      encoding: utf8
    mysql_grants_users:
    - name: testuser
      password: testpassword
      host: localhost
      priv: 'mytest.*:ALL'
      state: present

  roles:
  - name: andrelohmann.percona_mysql
  tasks:
  - name: Include andrelohmann.mysql_grants
    ansible.builtin.include_role:
      name: "andrelohmann.mysql_grants"
...
